name: Run checks

on: [push, pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: install nox
      run: python -m pip install nox
    - name: lint
      run: python -m nox -s lint

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
      fail-fast: false

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: install flatbuffers
      run: sudo apt-get install -y flatbuffers-compiler

    - name: install nox
      run: python -m pip install nox

    - name: Restore cached guest accounts
      uses: actions/cache@v3
      with:
        path: /tmp/arkprts_auth_cache.json
        key: guest-auth-cache-${{ matrix.python-version }}

    - name: Run tests
      run: |
        python -m nox -s test --verbose

  type-check:
    name: Type check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: install nox
      run: python -m pip install nox
    - name: Run pyright
      run: python -m nox -s type-check

  verify-types:
    name: Verify types
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: install nox
      run: python -m pip install nox
    - name: Run type checker
      run: python -m nox -s verify-types

  prettier:
    name: Prettier
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run prettier
      run: npx prettier --check *.md
